Updated workflow

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -16,31 +16,31 @@ jobs:
         run: npm run build
       - name: Commit
         run: |-
-        set -e
-        # get current commit hash
-        CURRENT_HASH=$(git rev-parse HEAD)
-        # get last commit hash of last build dist
-        LAST_BUILD_HASH=$(git log --author=github-actions -1 --pretty=format:"%H")
-        DIFF=""
-        # build and commit dist if diff
-        git config --global user.name github-actions
-        git config user.email 'github-actions@github.com'
-        git add dist/
-        git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
-        # if last commit hash of last build dist was found, get logs of commits in btw for PR body
-        if [ -z "$LAST_BUILD_HASH" ]
-        then
-              echo "Unable to find last commit by bot, skipping diff gen"
-        else
-              DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
-              echo $DIFF
-        fi
-        # set env vars
-        echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
-        echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
-        echo 'DIFF<<EOF' >> $GITHUB_ENV
-        echo "${DIFF}" >> $GITHUB_ENV
-        echo 'EOF' >> $GITHUB_ENV
+          set -e
+          # get current commit hash
+          CURRENT_HASH=$(git rev-parse HEAD)
+          # get last commit hash of last build dist
+          LAST_BUILD_HASH=$(git log --author=github-actions -1 --pretty=format:"%H")
+          DIFF=""
+          # build and commit dist if diff
+          git config --global user.name github-actions
+          git config user.email 'github-actions@github.com'
+          git add dist/
+          git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
+          # if last commit hash of last build dist was found, get logs of commits in btw for PR body
+          if [ -z "$LAST_BUILD_HASH" ]
+          then
+                echo "Unable to find last commit by bot, skipping diff gen"
+          else
+                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
+                echo $DIFF
+          fi
+          # set env vars
+          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
+          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
+          echo 'DIFF<<EOF' >> $GITHUB_ENV
+          echo "${DIFF}" >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
     - name: Create PR with dist
       uses: peter-evans/create-pull-request@v4
       with:
@@ -83,4 +83,25 @@ jobs:
       - build
       - release-please
     steps:
-        
+      - id: release-pr
+      - uses: google-github-actions/release-please-action@v3
+        id: release
+        with:
+          command: github-release
+          package-name: ${{env.ACTION_NAME}}
+          release-type: node
+      - uses: actions/checkout@v3
+      - id: label
+        if: ${{ steps.release-pr.outputs.pr }}
+        uses: actions/github-script@v3
+        with:
+            github-token: ${{secrets.GITHUB_TOKEN}}
+            script: |
+              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
+              await github.issues.addLabels({
+                owner,
+                repo,
+                issue_number: ${{steps.release-pr.outputs.pr}},
+                labels: ['autorelease: pending']
+              });
+              console.log(`Tagged ${{steps.release-pr.outputs.pr}}`)
