qwe

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -14,45 +14,45 @@ jobs:
         run: npm ci
       - name: Build
         run: npm run build
-      - name: Commit
-        run: |-
-          set -e
-          # get current commit hash
-          CURRENT_HASH=$(git rev-parse HEAD)
-          # get last commit hash of last build dist
-          LAST_BUILD_HASH=$(git log --author=github-actions -1 --pretty=format:"%H")
-          DIFF=""
-          # build and commit dist if diff
-          git config --global user.name github-actions
-          git config user.email 'github-actions@github.com'
-          git add dist/
-          git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
-          # if last commit hash of last build dist was found, get logs of commits in btw for PR body
-          if [ -z "$LAST_BUILD_HASH" ]
-          then
-                echo "Unable to find last commit by bot, skipping diff gen"
-          else
-                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
-                echo $DIFF
-          fi
-          # set env vars
-          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
-          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
-          echo 'DIFF<<EOF' >> $GITHUB_ENV
-          echo "${DIFF}" >> $GITHUB_ENV
-          echo 'EOF' >> $GITHUB_ENV
-    - name: Create PR with dist
-      uses: peter-evans/create-pull-request@v4
-      with:
-        commit-message: Build dist
-        title: "chore: build dist"
-        body: |
-          Build dist PR
-          ${{env.DIFF}}
-        labels: automated pr
-        branch: create-pull-request/build-dist
-        delete-branch: true
-        push-to-fork: google-github-actions-bot/${{env.ACTION_NAME}}
+      # - name: Commit
+      #   run: |-
+      #     set -e
+      #     # get current commit hash
+      #     CURRENT_HASH=$(git rev-parse HEAD)
+      #     # get last commit hash of last build dist
+      #     LAST_BUILD_HASH=$(git log --author=github-actions -1 --pretty=format:"%H")
+      #     DIFF=""
+      #     # build and commit dist if diff
+      #     git config --global user.name github-actions
+      #     git config user.email 'github-actions@github.com'
+      #     git add dist/
+      #     git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
+      #     # if last commit hash of last build dist was found, get logs of commits in btw for PR body
+      #     if [ -z "$LAST_BUILD_HASH" ]
+      #     then
+      #           echo "Unable to find last commit by bot, skipping diff gen"
+      #     else
+      #           DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
+      #           echo $DIFF
+      #     fi
+      #     # set env vars
+      #     echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
+      #     echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
+      #     echo 'DIFF<<EOF' >> $GITHUB_ENV
+      #     echo "${DIFF}" >> $GITHUB_ENV
+      #     echo 'EOF' >> $GITHUB_ENV
+    # - name: Create PR with dist
+    #   uses: peter-evans/create-pull-request@v4
+    #   with:
+    #     commit-message: Build dist
+    #     title: "chore: build dist"
+    #     body: |
+    #       Build dist PR
+    #       ${{env.DIFF}}
+    #     labels: automated pr
+    #     branch: create-pull-request/build-dist
+    #     delete-branch: true
+    #     push-to-fork: google-github-actions-bot/${{env.ACTION_NAME}}
   release-please:
     runs-on: ubuntu-latest
     needs: [build]
@@ -63,20 +63,20 @@ jobs:
           command: github-release
           package-name: ${{env.ACTION_NAME}}
           release-type: node
-      - uses: actions/checkout@v3
-      - name: Tag major and minor versions
-        if: ${{ steps.release.outputs.release_created }}
-        run: |
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git tag -d v${{ steps.release.outputs.major }} || true
-          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
-          git push origin :v${{ steps.release.outputs.major }} || true
-          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
-          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
-          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
-          git push origin v${{ steps.release.outputs.major }}
-          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
+      # - uses: actions/checkout@v3
+      # - name: Tag major and minor versions
+      #   if: ${{ steps.release.outputs.release_created }}
+      #   run: |
+      #     git config user.name github-actions
+      #     git config user.email github-actions@github.com
+      #     git tag -d v${{ steps.release.outputs.major }} || true
+      #     git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
+      #     git push origin :v${{ steps.release.outputs.major }} || true
+      #     git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
+      #     git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
+      #     git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
+      #     git push origin v${{ steps.release.outputs.major }}
+      #     git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
   pull-request:
     runs-on: ubuntu-latest
     needs:
@@ -90,18 +90,18 @@ jobs:
           command: github-release
           package-name: ${{env.ACTION_NAME}}
           release-type: node
-      - uses: actions/checkout@v3
-      - id: label
-        if: ${{ steps.release-pr.outputs.pr }}
-        uses: actions/github-script@v3
-        with:
-            github-token: ${{secrets.GITHUB_TOKEN}}
-            script: |
-              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
-              await github.issues.addLabels({
-                owner,
-                repo,
-                issue_number: ${{steps.release-pr.outputs.pr}},
-                labels: ['autorelease: pending']
-              });
-              console.log(`Tagged ${{steps.release-pr.outputs.pr}}`)
+      # - uses: actions/checkout@v3
+      # - id: label
+      #   if: ${{ steps.release-pr.outputs.pr }}
+      #   uses: actions/github-script@v3
+      #   with:
+      #       github-token: ${{secrets.GITHUB_TOKEN}}
+      #       script: |
+      #         const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
+      #         await github.issues.addLabels({
+      #           owner,
+      #           repo,
+      #           issue_number: ${{steps.release-pr.outputs.pr}},
+      #           labels: ['autorelease: pending']
+      #         });
+      #         console.log(`Tagged ${{steps.release-pr.outputs.pr}}`)
